open_manipulator_x_master_slave:
  ros__parameters:
    service_call_period: 0.010
    joint01_id: 1
    joint02_id: 2
    joint03_id: 3
    joint04_id: 4
    joint05_id: 5
    joint06_id: 6
    gripper01_id: 7
